name: build

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Build
        run: poetry install

      - name: Lint
        run: poetry run flake8 .

      - name: Test
        run: poetry run python ./tests/AvatarValidatorTests.py
